"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .environment import create_environment_configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENVIRONMENT = create_environment_configuration(BASE_DIR)


# Security
# https://docs.djangoproject.com/en/5.2/topics/security/

SECRET_KEY = ENVIRONMENT.management.security.secret_key
DEBUG = ENVIRONMENT.management.security.debug
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "access_control",
    "credentials",
    "runtimes",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'

# The template engine that renders workspace configuration files rather than HTML.
CONFIG_TEMPLATE_ENGINE = "configs"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        # Renders supervisord and nginx configuration. HTML escaping would corrupt quotes and
        # ampersands in command lines, so this engine has it switched off.
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'NAME': CONFIG_TEMPLATE_ENGINE,
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'autoescape': False,
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": ENVIRONMENT.management.database.name,
        "USER": ENVIRONMENT.management.database.user,
        "PASSWORD": ENVIRONMENT.management.database.password,
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uvicorn serves no static files by itself, so WhiteNoise does it. Admin is the only frontend, so
# its files come straight from the staticfiles finders. That skips collectstatic and a STATIC_ROOT,
# and makes DEBUG=false behave like DEBUG=true, which both default to for this setting.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Management service settings

GPGHOME = ENVIRONMENT.management.credentials.gpghome

# The full control key, scheme prefix included, as used by the invoke CLI on the host.
# When it is unset no caller can authenticate as control and the CLI receives a 401.
CONTROL_API_KEY = ENVIRONMENT.management.security.api_key


# Process control over the supervisord in the workspaces container. The URL resolves both from the
# management container and from the host, where install.hosts-file maps the service names.

SUPERVISOR_URL = ENVIRONMENT.workspaces.supervisor.url
SUPERVISOR_USERNAME = ENVIRONMENT.workspaces.supervisor.username
SUPERVISOR_PASSWORD = ENVIRONMENT.workspaces.supervisor.password
SUPERVISOR_CLIENT = "runtimes.supervisor.XmlRpcSupervisorClient"
