# Generated by Django 5.2.12 on 2026-08-06 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0003_workspace_api_key_created_at_workspace_api_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.SlugField(max_length=64)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('port', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='access_control.workspace')),
            ],
            options={
                'ordering': ('workspace__module', 'name'),
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SupervisordRuntime',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('runtimes.runtime',),
        ),
        migrations.CreateModel(
            name='CeleryRuntime',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('runtimes.supervisordruntime',),
        ),
        migrations.CreateModel(
            name='HttpRuntime',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('runtimes.supervisordruntime',),
        ),
        migrations.CreateModel(
            name='DjangoRuntime',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('runtimes.httpruntime',),
        ),
    ]
