# Generated by Django 5.2.12 on 2026-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtimes', '0002_runtime_installed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='module',
            field=models.CharField(default='web', max_length=255),
        ),
    ]
