# Generated by Django 5.2.12 on 2026-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_remove_workspace_django_module'),
        ('runtimes', '0003_runtime_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='runtime',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('workspace',), name='runtime_unique_primary'),
        ),
    ]
