import pytest

from access_control.models import Workspace
from runtimes.configs import build_manifest, render_supervisord_environment
from runtimes.models import Runtime


@pytest.fixture
def workspace(db) -> Workspace:
    return Workspace.objects.create(name="Magic Match", module="magic_match")


@pytest.fixture
def django_runtime(workspace) -> Runtime:
    return Runtime.objects.create(workspace=workspace, type="django", name="web", port=8001)


@pytest.fixture
def celery_runtime(workspace) -> Runtime:
    return Runtime.objects.create(
        workspace=workspace, type="celery", name="worker", configuration={"queues": ["default"]},
    )


def config_by_path(runtime: Runtime) -> dict[str, str]:
    return {config.path: config.content for config in runtime.specialize().config_files()}


@pytest.mark.django_db
def test_django_runtime_renders_supervisord_and_nginx(django_runtime):
    configs = config_by_path(django_runtime)

    assert sorted(configs) == [
        "nginx/magic_match/web.conf",
        "supervisor/magic_match/web.conf",
    ]


@pytest.mark.django_db
def test_celery_runtime_renders_supervisord_only(celery_runtime):
    # No port, no server block. Nothing to proxy to.
    assert sorted(config_by_path(celery_runtime)) == ["supervisor/magic_match/worker.conf"]


@pytest.mark.django_db
def test_django_supervisord_config(django_runtime):
    content = config_by_path(django_runtime)["supervisor/magic_match/web.conf"]

    assert content == (
        '; Generated by the Just Build management API for runtime "web".\n'
        "; Edits are discarded the next time `invoke runtimes.apply` reconciles this tree.\n"
        "[program:magic_match_web]\n"
        "command=/home/magic_match/venv/bin/python -m uvicorn web.asgi:application"
        " --host 127.0.0.1 --port 8001 --workers 2 --loop uvloop --http httptools\n"
        "directory=/home/magic_match\n"
        "user=magic_match\n"
        "autostart=true\n"
        "autorestart=true\n"
        "stopasgroup=true\n"
        "killasgroup=true\n"
        "redirect_stderr=true\n"
        "stdout_logfile=/var/log/workspaces/magic_match/web.log\n"
        "stdout_logfile_maxbytes=50MB\n"
        "stdout_logfile_backups=5\n"
        "environment=\n"
        '    DJANGO_SETTINGS_MODULE="web.settings",\n'
        '    PYTHONPATH="/home/magic_match"\n'
    )


@pytest.mark.django_db
def test_celery_supervisord_config(celery_runtime):
    content = config_by_path(celery_runtime)["supervisor/magic_match/worker.conf"]

    assert "[program:magic_match_worker]" in content
    assert "command=/home/magic_match/venv/bin/python -m celery --app web worker" in content
    assert "--queues default" in content
    assert "stdout_logfile=/var/log/workspaces/magic_match/worker.log" in content
    assert "user=magic_match" in content


@pytest.mark.django_db
def test_nginx_config(django_runtime):
    content = config_by_path(django_runtime)["nginx/magic_match/web.conf"]

    assert "upstream magic_match_web_upstream {" in content
    assert "server 127.0.0.1:8001 fail_timeout=0;" in content
    assert "server_name magic-match.localhost;" in content
    assert "alias /home/magic_match/staticfiles/;" in content
    assert "proxy_pass http://magic_match_web_upstream;" in content


@pytest.mark.django_db
def test_nginx_config_honours_a_configured_domain(workspace):
    runtime = Runtime.objects.create(
        workspace=workspace, type="django", name="web", port=8001,
        configuration={"domain": "magic.example.test"},
    )

    assert "server_name magic.example.test;" in config_by_path(runtime)["nginx/magic_match/web.conf"]


@pytest.mark.django_db
def test_rendering_does_not_escape_html_characters(workspace):
    # Autoescaping would turn the ampersand and quotes into entities and break the ini file.
    runtime = Runtime.objects.create(
        workspace=workspace, type="celery", name="worker",
        configuration={"environment": {"NOTE": "tom & jerry's <quotes>"}},
    )

    content = config_by_path(runtime)["supervisor/magic_match/worker.conf"]

    assert 'NOTE="tom & jerry\'s <quotes>"' in content
    assert "&amp;" not in content


def test_environment_line_doubles_percent_signs():
    # supervisord expands %(...)s itself, so a literal percent has to survive as %%.
    rendered = render_supervisord_environment({"FORMAT": "100%"})

    assert rendered == '\n    FORMAT="100%%"'


def test_empty_environment_renders_nothing():
    assert render_supervisord_environment({}) == ""


@pytest.mark.django_db
def test_manifest_covers_every_runtime_and_is_ordered(django_runtime, celery_runtime):
    manifest = build_manifest(Runtime.objects.all())

    assert [config.path for config in manifest] == [
        "nginx/magic_match/web.conf",
        "supervisor/magic_match/web.conf",
        "supervisor/magic_match/worker.conf",
    ]


@pytest.mark.django_db
def test_manifest_separates_workspaces(django_runtime):
    other = Workspace.objects.create(name="Other", module="other")
    Runtime.objects.create(workspace=other, type="django", name="web", port=8002)

    manifest = build_manifest(Runtime.objects.all())

    assert [config.path for config in manifest] == [
        "nginx/magic_match/web.conf",
        "nginx/other/web.conf",
        "supervisor/magic_match/web.conf",
        "supervisor/other/web.conf",
    ]
