# Generated by Django 5.2.12 on 2026-08-09 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0005_remove_workspace_django_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('n8n_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tags', to='access_control.workspace')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('n8n_id', models.CharField(blank=True, default='', max_length=64)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('pulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='access_control.workspace')),
                ('tags', models.ManyToManyField(blank=True, related_name='workflows', to='workflows.workflowtag')),
            ],
            options={
                'ordering': ('workspace__module', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtag',
            constraint=models.UniqueConstraint(condition=models.Q(('n8n_id', ''), _negated=True), fields=('n8n_id',), name='workflow_tag_unique_n8n_id'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('n8n_id', ''), _negated=True), fields=('n8n_id',), name='workflow_unique_n8n_id'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='workflow_unique_workspace_slug'),
        ),
    ]
