# Generated by Django 5.2.12 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_workspace_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='api_key_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
