# Generated by Django 5.2.12 on 2026-08-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_workspace_git_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='django_module',
        ),
    ]
