from pathlib import Path
from uuid import UUID

from django.db import IntegrityError
from django.conf import settings
from django.http import HttpRequest, HttpResponse
from ninja import ModelSchema, Router, Schema
from ninja.errors import HttpError

from access_control.models import Project


controller = Router()


class ProjectSSHSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class ProjectSchema(Schema):
    id: UUID
    name: str
    slug: str
    django_module: str
    setup: dict[str, str]
    ssh: ProjectSSHSchema


class ProjectCreateSchema(ModelSchema):
    class Meta:
        model = Project
        fields = ["name", "slug", "django_module"]


class ProjectSSHPatchSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class ProjectPatchSchema(Schema):
    setup: dict[str, str] | None = None
    ssh: ProjectSSHPatchSchema | None = None


def get_project_or_404(project_slug: str) -> Project:
    try:
        return Project.objects.get(slug=project_slug)
    except Project.DoesNotExist as exc:
        raise HttpError(404, "Project not found") from exc


def build_ssh_config(projects: list[Project]) -> str:
    lines = [
        "# Automatically generated by the Just Build management API.",
        "# Do not edit this file directly.",
        "",
    ]

    repo_root = settings.BASE_DIR.parent

    for project in projects:
        ssh = ProjectSSHSchema.model_validate(project.ssh or {})
        if not all([ssh.alias, ssh.user, ssh.host, ssh.port, ssh.identity_file]):
            continue

        identity_file = Path(ssh.identity_file).expanduser()
        if not identity_file.is_absolute():
            identity_file = repo_root / identity_file

        lines.extend(
            [
                f"Host {ssh.alias}",
                f"    HostName {ssh.host}",
                f"    Port {ssh.port}",
                f"    User {ssh.user}",
                f"    IdentityFile {identity_file}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


@controller.post("/", response={201: ProjectSchema}, tags=["Projects"])
def create_project(request: HttpRequest, data: ProjectCreateSchema) -> tuple[int, Project]:
    try:
        project = Project.objects.create(**data.model_dump())
    except IntegrityError as exc:
        raise HttpError(409, "Project already exists") from exc
    return 201, project


@controller.get("/", response=list[ProjectSchema], tags=["Projects"])
def list_projects(request: HttpRequest) -> list[Project]:
    return list(Project.objects.order_by("name"))


@controller.get("/ssh-config/", tags=["Projects"])
def get_ssh_config(request: HttpRequest) -> HttpResponse:
    projects = list(Project.objects.order_by("name"))
    return HttpResponse(build_ssh_config(projects), content_type="text/plain; charset=utf-8")


@controller.patch("/{project_slug}/", response=ProjectSchema, tags=["Projects"])
def patch_project(request: HttpRequest, project_slug: str, data: ProjectPatchSchema) -> Project:
    project = get_project_or_404(project_slug)
    update_fields: list[str] = []

    payload = data.model_dump(exclude_none=True)
    setup_updates = payload.pop("setup", None)
    if setup_updates:
        project.setup = {**project.setup, **setup_updates}
        update_fields.append("setup")

    ssh_updates = payload.pop("ssh", None)
    if ssh_updates:
        project.ssh = {**project.ssh, **ssh_updates}
        update_fields.append("ssh")

    if update_fields:
        project.save(update_fields=update_fields)

    return project


@controller.get("/{project_slug}/", response=ProjectSchema, tags=["Projects"])
def get_project(request: HttpRequest, project_slug: str) -> Project:
    return get_project_or_404(project_slug)
