from pathlib import Path
from uuid import UUID

from django.db import IntegrityError
from django.http import HttpRequest, HttpResponse
from ninja import ModelSchema, Router, Schema
from ninja.errors import HttpError

from access_control.authentication import Principal, control_api_key_auth
from access_control.models import Workspace


controller = Router()


class WorkspaceSSHSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class WorkspaceSchema(Schema):
    id: UUID
    name: str
    module: str
    slug: str
    setup: dict[str, str]
    ssh: WorkspaceSSHSchema
    git_public_key: str


class WorkspaceCreateSchema(ModelSchema):
    class Meta:
        model = Workspace
        fields = ["name", "module"]


class WorkspaceSSHPatchSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class WorkspacePatchSchema(Schema):
    setup: dict[str, str] | None = None
    ssh: WorkspaceSSHPatchSchema | None = None
    git_public_key: str | None = None


class WorkspaceCreatedSchema(WorkspaceSchema):
    """Workspace plus the plaintext API key, which is only ever returned here and from rotate-key."""
    api_key: str


class WorkspaceApiKeySchema(Schema):
    module: str
    api_key: str


def get_workspace_or_404(request: HttpRequest, workspace_module: str) -> Workspace:
    """
    Resolve a workspace within the caller's scope.

    Out-of-scope workspaces are indistinguishable from missing ones, so a workspace cannot confirm
    that another workspace exists by asking for it.
    """
    principal: Principal = request.auth
    try:
        return principal.workspaces().get(module=workspace_module)
    except Workspace.DoesNotExist as exc:
        raise HttpError(404, "Workspace not found") from exc


def build_ssh_config(workspaces: list[Workspace], repository_root: Path) -> str:
    lines = [
        "# Automatically generated by the Just Build management API.",
        "# Do not edit this file directly.",
        "",
    ]

    for workspace in workspaces:
        ssh = WorkspaceSSHSchema.model_validate(workspace.ssh or {})
        if not all([ssh.alias, ssh.user, ssh.host, ssh.port, ssh.identity_file]):
            continue

        identity_file = Path(ssh.identity_file).expanduser()
        if not identity_file.is_absolute():
            identity_file = repository_root / identity_file

        lines.extend(
            [
                f"Host {ssh.alias}",
                f"    HostName {ssh.host}",
                f"    Port {ssh.port}",
                f"    User {ssh.user}",
                f"    IdentityFile {identity_file}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


@controller.post("/", response={201: WorkspaceCreatedSchema}, auth=control_api_key_auth, tags=["Workspaces"])
def create_workspace(request: HttpRequest, data: WorkspaceCreateSchema) -> tuple[int, Workspace]:
    workspace = Workspace(**data.model_dump())
    api_key = workspace.issue_api_key()
    try:
        workspace.save()
    except IntegrityError as exc:
        raise HttpError(409, "Workspace already exists") from exc
    workspace.api_key = api_key
    return 201, workspace


@controller.get("/", response=list[WorkspaceSchema], tags=["Workspaces"])
def list_workspaces(request: HttpRequest) -> list[Workspace]:
    return list(request.auth.workspaces().order_by("name"))


@controller.get("/ssh-config/", auth=control_api_key_auth, tags=["Workspaces"])
def get_ssh_config(request: HttpRequest, repository_root: str) -> HttpResponse:
    """
    Render the config for the caller's checkout.

    Identity files are stored relative to the repository, and management cannot resolve them itself:
    it runs in a container where the repository sits at another path, so anything it worked out from
    its own location would name a file that exists on no host.
    """
    root = Path(repository_root)
    if not root.is_absolute():
        raise HttpError(422, "repository_root must be an absolute path")

    workspaces = list(Workspace.objects.order_by("name"))
    return HttpResponse(build_ssh_config(workspaces, root), content_type="text/plain; charset=utf-8")


@controller.post("/{workspace_module}/rotate-key/", response=WorkspaceApiKeySchema, auth=control_api_key_auth,
                 tags=["Workspaces"])
def rotate_workspace_api_key(request: HttpRequest, workspace_module: str) -> WorkspaceApiKeySchema:
    workspace = get_workspace_or_404(request, workspace_module)
    api_key = workspace.issue_api_key()
    return WorkspaceApiKeySchema(module=workspace.module, api_key=api_key)


@controller.patch("/{workspace_module}/", response=WorkspaceSchema, auth=control_api_key_auth, tags=["Workspaces"])
def patch_workspace(request: HttpRequest, workspace_module: str, data: WorkspacePatchSchema) -> Workspace:
    workspace = get_workspace_or_404(request, workspace_module)
    update_fields: list[str] = []

    payload = data.model_dump(exclude_none=True)
    setup_updates = payload.pop("setup", None)
    if setup_updates:
        workspace.setup = {**workspace.setup, **setup_updates}
        update_fields.append("setup")

    ssh_updates = payload.pop("ssh", None)
    if ssh_updates:
        workspace.ssh = {**workspace.ssh, **ssh_updates}
        update_fields.append("ssh")

    git_public_key = payload.pop("git_public_key", None)
    if git_public_key is not None:
        workspace.git_public_key = git_public_key.strip()
        update_fields.append("git_public_key")

    if update_fields:
        workspace.save(update_fields=update_fields)

    return workspace


@controller.get("/{workspace_module}/", response=WorkspaceSchema, tags=["Workspaces"])
def get_workspace(request: HttpRequest, workspace_module: str) -> Workspace:
    return get_workspace_or_404(request, workspace_module)


@controller.delete("/{workspace_module}/", response={204: None}, auth=control_api_key_auth, tags=["Workspaces"])
def delete_workspace(request: HttpRequest, workspace_module: str) -> tuple[int, None]:
    workspace = get_workspace_or_404(request, workspace_module)
    workspace.delete()
    return 204, None
