from pathlib import Path
from uuid import UUID

from django.db import IntegrityError
from django.conf import settings
from django.http import HttpRequest, HttpResponse
from ninja import ModelSchema, Router, Schema
from ninja.errors import HttpError

from access_control.models import Workspace


controller = Router()


class WorkspaceSSHSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class WorkspaceSchema(Schema):
    id: UUID
    name: str
    module: str
    slug: str
    django_module: str
    setup: dict[str, str]
    ssh: WorkspaceSSHSchema


class WorkspaceCreateSchema(ModelSchema):
    class Meta:
        model = Workspace
        fields = ["name", "module", "django_module"]


class WorkspaceSSHPatchSchema(Schema):
    alias: str | None = None
    user: str | None = None
    host: str | None = None
    port: int | None = None
    identity_file: str | None = None


class WorkspacePatchSchema(Schema):
    setup: dict[str, str] | None = None
    ssh: WorkspaceSSHPatchSchema | None = None


def get_workspace_or_404(workspace_module: str) -> Workspace:
    try:
        return Workspace.objects.get(module=workspace_module)
    except Workspace.DoesNotExist as exc:
        raise HttpError(404, "Workspace not found") from exc


def build_ssh_config(workspaces: list[Workspace]) -> str:
    lines = [
        "# Automatically generated by the Just Build management API.",
        "# Do not edit this file directly.",
        "",
    ]

    repo_root = settings.BASE_DIR.parent

    for workspace in workspaces:
        ssh = WorkspaceSSHSchema.model_validate(workspace.ssh or {})
        if not all([ssh.alias, ssh.user, ssh.host, ssh.port, ssh.identity_file]):
            continue

        identity_file = Path(ssh.identity_file).expanduser()
        if not identity_file.is_absolute():
            identity_file = repo_root / identity_file

        lines.extend(
            [
                f"Host {ssh.alias}",
                f"    HostName {ssh.host}",
                f"    Port {ssh.port}",
                f"    User {ssh.user}",
                f"    IdentityFile {identity_file}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


@controller.post("/", response={201: WorkspaceSchema}, tags=["Workspaces"])
def create_workspace(request: HttpRequest, data: WorkspaceCreateSchema) -> tuple[int, Workspace]:
    try:
        workspace = Workspace.objects.create(**data.model_dump())
    except IntegrityError as exc:
        raise HttpError(409, "Workspace already exists") from exc
    return 201, workspace


@controller.get("/", response=list[WorkspaceSchema], tags=["Workspaces"])
def list_workspaces(request: HttpRequest) -> list[Workspace]:
    return list(Workspace.objects.order_by("name"))


@controller.get("/ssh-config/", tags=["Workspaces"])
def get_ssh_config(request: HttpRequest) -> HttpResponse:
    workspaces = list(Workspace.objects.order_by("name"))
    return HttpResponse(build_ssh_config(workspaces), content_type="text/plain; charset=utf-8")


@controller.patch("/{workspace_module}/", response=WorkspaceSchema, tags=["Workspaces"])
def patch_workspace(request: HttpRequest, workspace_module: str, data: WorkspacePatchSchema) -> Workspace:
    workspace = get_workspace_or_404(workspace_module)
    update_fields: list[str] = []

    payload = data.model_dump(exclude_none=True)
    setup_updates = payload.pop("setup", None)
    if setup_updates:
        workspace.setup = {**workspace.setup, **setup_updates}
        update_fields.append("setup")

    ssh_updates = payload.pop("ssh", None)
    if ssh_updates:
        workspace.ssh = {**workspace.ssh, **ssh_updates}
        update_fields.append("ssh")

    if update_fields:
        workspace.save(update_fields=update_fields)

    return workspace


@controller.get("/{workspace_module}/", response=WorkspaceSchema, tags=["Workspaces"])
def get_workspace(request: HttpRequest, workspace_module: str) -> Workspace:
    return get_workspace_or_404(workspace_module)


@controller.delete("/{workspace_module}/", response={204: None}, tags=["Workspaces"])
def delete_workspace(request: HttpRequest, workspace_module: str) -> tuple[int, None]:
    workspace = get_workspace_or_404(workspace_module)
    workspace.delete()
    return 204, None
