import importlib
from types import SimpleNamespace

import pytest


adopt_cli = importlib.import_module("workspaces.cli.runtimes.adopt")


LEGACY_SUPERVISOR_CONFIG = """; Automatically generated by invoke workspaces.create.
[program:demo]
command=/home/demo/venv/bin/python -m uvicorn web.asgi:application --host 127.0.0.1 --port 8007 --workers 2
directory=/home/demo
stdout_logfile=/var/log/projects/demo.log
"""

LEGACY_NGINX_CONFIG = """upstream demo_upstream {
    server 127.0.0.1:8007 fail_timeout=0;
}

server {
    listen 7000;
    server_name demo.localhost;
}
"""


def test_read_legacy_port_finds_the_uvicorn_port(tmp_path):
    config = tmp_path / "demo.conf"
    config.write_text(LEGACY_SUPERVISOR_CONFIG)

    assert adopt_cli.read_legacy_port(config) == 8007


def test_read_legacy_port_returns_none_without_a_config(tmp_path):
    assert adopt_cli.read_legacy_port(tmp_path / "missing.conf") is None


def test_read_legacy_domain_finds_the_server_name(tmp_path):
    config = tmp_path / "demo.conf"
    config.write_text(LEGACY_NGINX_CONFIG)

    assert adopt_cli.read_legacy_domain(config) == "demo.localhost"


def test_read_legacy_domain_skips_the_catch_all_server(tmp_path):
    config = tmp_path / "demo.conf"
    config.write_text("server {\n    server_name _;\n}\n")

    assert adopt_cli.read_legacy_domain(config) is None


@pytest.fixture
def adoption(tmp_path, monkeypatch):
    """A workspace with the pre-runtimes layout on disk and no runtimes in management."""
    supervisor_dir = tmp_path / "supervisor"
    nginx_dir = tmp_path / "nginx"
    supervisor_dir.mkdir()
    nginx_dir.mkdir()
    (supervisor_dir / "demo.conf").write_text(LEGACY_SUPERVISOR_CONFIG)
    (nginx_dir / "demo.conf").write_text(LEGACY_NGINX_CONFIG)

    monkeypatch.setattr(adopt_cli, "SUPERVISOR_DIR", supervisor_dir)
    monkeypatch.setattr(adopt_cli, "NGINX_DIR", nginx_dir)
    monkeypatch.setattr(adopt_cli, "get_workspace", lambda module: SimpleNamespace(name="Demo", module=module))

    created: list[dict] = []
    calls: list[tuple] = []

    def create_runtime(workspace_module, runtime_type, name, configuration=None, port=None):
        created.append({
            "workspace_module": workspace_module, "type": runtime_type, "name": name,
            "configuration": configuration, "port": port,
        })
        return SimpleNamespace(
            id="runtime-id", name=name, program_name=f"{workspace_module}_{name}", port=port,
            log_path=f"/var/log/workspaces/{workspace_module}/{name}.log",
        )

    monkeypatch.setattr(adopt_cli.client, "list_runtimes", lambda module: [])
    monkeypatch.setattr(adopt_cli.client, "create_runtime", create_runtime)
    monkeypatch.setattr(
        adopt_cli.client, "set_runtime_enabled",
        lambda runtime_id, enabled: calls.append(("enable", runtime_id, enabled)),
    )
    monkeypatch.setattr(adopt_cli, "apply_configs", lambda ctx: calls.append(("apply",)))

    return SimpleNamespace(created=created, calls=calls)


def test_adopt_keeps_the_port_and_domain_the_workspace_already_serves(adoption):
    adopt_cli.adopt.body(object(), "demo")

    # Changing either would break the running workspace, so both come from the old config.
    assert adoption.created == [{
        "workspace_module": "demo", "type": "django", "name": "web",
        "configuration": {"domain": "demo.localhost"}, "port": 8007,
    }]


def test_adopt_enables_and_applies(adoption):
    adopt_cli.adopt.body(object(), "demo")

    assert adoption.calls == [("enable", "runtime-id", True), ("apply",)]


def test_adopt_accepts_a_port_override(adoption):
    adopt_cli.adopt.body(object(), "demo", port=9100)

    assert adoption.created[0]["port"] == 9100


def test_adopt_is_a_no_op_when_the_runtime_already_exists(adoption, monkeypatch, capsys):
    monkeypatch.setattr(
        adopt_cli.client, "list_runtimes", lambda module: [SimpleNamespace(name="web")],
    )

    adopt_cli.adopt.body(object(), "demo")

    assert adoption.created == []
    assert adoption.calls == []
    assert "Nothing to adopt" in capsys.readouterr().out


def test_adopt_falls_back_to_allocation_without_a_legacy_config(adoption, monkeypatch, tmp_path, capsys):
    monkeypatch.setattr(adopt_cli, "SUPERVISOR_DIR", tmp_path / "empty")

    adopt_cli.adopt.body(object(), "demo")

    assert adoption.created[0]["port"] is None
    assert "letting management allocate one" in capsys.readouterr().out
